name: Déploiement automatique du CV

on:
  push:
    branches:
      - main  # Le déploiement se lance à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Déploie tout le contenu du dossier racine